apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment_name }}
  namespace: {{ .Values.name_space }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.deployment_name }}
  template:
    metadata:
      labels:
        name: {{ .Values.deployment_name }}
        tier: database
      annotations:
        buildid: "{{ .Values.build_id }}"
    spec:
      hostname: {{ .Values.deployment_name }}
      volumes:
      - name: {{ .Values.pv_name }}
        persistentVolumeClaim:
            claimName: {{ .Values.pvc_name }}
      containers:
      - name: {{ .Values.deployment_name }}
        image: {{ .Values.image_id }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
           secretKeyRef:
            name: wiki-secrets
            key: wikidb_root_password
        - name: MYSQL_DATABASE
          value: {{ .Values.wiki_db }}
        - name: MYSQL_USER
          value: "wiki"
        - name: {{ .Values.wiki_user }}
          valueFrom:
           secretKeyRef:
            name: wiki-secrets
            key: wiki_password
        ports:
        - containerPort: {{ .Values.container_port }}
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory}}
            cpu: {{ .Values.resources.limits.cpu}}
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: {{ .Values.pv_name }}