apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc_name }}
  namespace: {{ .Values.name_space }}
spec:
  accessModes:
    - {{ .Values.pv_access_mode }}
  resources:
    requests:
      storage: {{ .Values.pvc_size }}
  storageClassName: {{ .Values.storage_class }}