apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment_name }}
  namespace: {{ .Values.name_space }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.deployment_name }}
  template:
    metadata:
      labels:
        name: {{ .Values.deployment_name }}
        tier: frontend
      annotations:
        buildid: "{{ .Values.build_id }}"
    spec:
      hostname: {{ .Values.deployment_name }}
      containers:
      - name: {{ .Values.deployment_name }}
        image: {{ .Values.image_id }}
        ports:
        - containerPort: {{ .Values.container_port }}
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }} 
            cpu: {{ .Values.resources.limits.cpu }}